"""
LLM-powered explanation generator for MindReader.

Replaces the rule-based explain_recommendation() with natural, curator-style
explanations generated by Groq (llama-3.3-70b-versatile).

Falls back to the original rule-based explanation if the API call fails.

Usage:
    env/bin/python src/explainer.py
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv
load_dotenv(Path(__file__).parent.parent / ".env")

sys.path.insert(0, os.path.dirname(__file__))

from groq import Groq
from recommender import load_songs, recommend_songs

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

SYSTEM_PROMPT = """You are a music curator known for warm, specific, and honest recommendations.
Given a listener's preferences and a list of recommended songs, write one sentence per song
explaining exactly why it suits this listener.
Be specific — reference the mood, energy level, genre, or acoustic texture.
Do not use generic phrases like "this song is perfect for you."
Return only a numbered list matching the order of the songs, no extra text."""


def _format_profile(user_prefs: dict) -> str:
    acoustic = "acoustic" if user_prefs["likes_acoustic"] else "non-acoustic"
    return (
        f"Genre: {user_prefs['favorite_genre']} | "
        f"Mood: {user_prefs['favorite_mood']} | "
        f"Target energy: {user_prefs['target_energy']} | "
        f"Style: {acoustic}"
    )


def _format_songs(recs: list) -> str:
    lines = []
    for i, (song, score, _) in enumerate(recs, 1):
        lines.append(
            f"{i}. \"{song['title']}\" by {song['artist']} "
            f"[genre: {song['genre']}, mood: {song['mood']}, "
            f"energy: {song['energy']}, acousticness: {song['acousticness']}]"
        )
    return "\n".join(lines)


def explain_with_llm(user_prefs: dict, recs: list) -> list[str]:
    """
    Returns a list of one-sentence explanations (one per recommendation).
    Falls back to the original rule-based reasons on any API error.
    """
    if not recs:
        return []

    prompt = (
        f"Listener profile: {_format_profile(user_prefs)}\n\n"
        f"Recommended songs:\n{_format_songs(recs)}"
    )

    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            temperature=0.6,
            max_tokens=400,
        )
        raw = response.choices[0].message.content.strip()
        lines = [ln.lstrip("0123456789. ").strip() for ln in raw.splitlines() if ln.strip()]
        # Ensure we have one explanation per song; pad with fallback if needed
        explanations = lines[:len(recs)]
        while len(explanations) < len(recs):
            explanations.append(recs[len(explanations)][2])  # original rule-based reason
        return explanations

    except Exception as e:
        print(f"[explainer] API error — falling back to rule-based explanations: {e}")
        return [reason for _, _, reason in recs]


def main():
    songs = load_songs("data/songs.csv")

    profiles = {
        "Lofi Studier": {
            "favorite_genre": "lofi",
            "favorite_mood": "focused",
            "target_energy": 0.38,
            "likes_acoustic": True,
        },
        "Gym Grinder": {
            "favorite_genre": "metal",
            "favorite_mood": "intense",
            "target_energy": 0.95,
            "likes_acoustic": False,
        },
    }

    for name, prefs in profiles.items():
        recs = recommend_songs(prefs, songs, k=3)
        explanations = explain_with_llm(prefs, recs)

        print(f"\n{'=' * 55}")
        print(f"  {name}")
        print(f"{'=' * 55}")
        for (song, score, _), explanation in zip(recs, explanations):
            print(f"\n  {song['title']} by {song['artist']}  (score: {score:.2f})")
            print(f"  → {explanation}")


if __name__ == "__main__":
    main()
